---
- name: 1. install Apache
  apt: name=apache2 state=present

- name: 2. install PHP module for Apache
  apt: name = {{item}} state=present
  with_items :
    -libapache2-mod-php5

- name: 3. start Apache
  service: name=apache2 state=started enabled=yes
